{% set name = "pprofile" %}
{% set version = "2.0.0" %}
{% set sha256 = "1750aa78105ac3f2d46855c8a49157356ed14b0beda858056850e3da87896ba0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - pprofile = pprofile:main

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pprofile
    - zpprofile
  commands:
    - pprofile --help

about:
  home: http://github.com/vpelletier/pprofile
  license: GPL2
  license_file: COPYING
  summary: Line-granularity, thread-aware deterministic and statistic pure-python profiler

extra:
  recipe-maintainers:
    - jakirkham
