{% set name = "pprofile" %}
{% set version = "2.2.0" %}
{% set sha256 = "edd57f35f2b3fb84e7d01aa310a44bfabacc66ffc353dce147348ec14de3c7d9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - pprofile = pprofile:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - pprofile
    - zpprofile
  commands:
    - pprofile --help

about:
  home: http://github.com/vpelletier/pprofile
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Line-granularity, thread-aware deterministic and statistic pure-python profiler

extra:
  recipe-maintainers:
    - jakirkham
