{% set name = "pprofile" %}
{% set version = "1.11.0" %}
{% set sha256 = "301f465a97cc965c60111a0609552a877a699562b06a3205ee6c291b835c416b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - pprofile = pprofile:main

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pprofile
    - zpprofile
  commands:
    - pprofile --help

about:
  home: http://github.com/vpelletier/pprofile
  license: GPL2
  # PyPI missing license file. Added PR to add it to future sdists.
  #
  # xref: https://github.com/vpelletier/pprofile/pull/17
  #
  #license_file: COPYING
  summary: Line-granularity, thread-aware deterministic and statistic pure-python profiler

extra:
  recipe-maintainers:
    - jakirkham
