appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kaIz3dWQdJT5ZZyZZLSY7aMSxu5LzyYNSKkIBa0JS/gnsYyXofCiAynZb/yrWMYoKDoTRVMuA1j9nwB0ePkMzWjfKgzBNENoHV1Dbw5nVGZfO0i0vwLAQFdsL6N8++hxPdc4h25nK2x44iJ6fBr5l/4XURiD+06U0nVTyBc8ZkhWbfZVSF54xA1MIsoX5ZhIRToTf0A/AJ7uuMFri/V+Jt5ENbjp5/ZwKTDXG9TNWLq//wdSnBiS6LWCC31z5zfGmKRThl7XXKAg0wUk5W2s0qZXx/oc63goCnFglb05/LBfQtWIDDf3Np3ZyA/qjnC05eh6BCGCUD+DVu+LjI9Pq5siFpQYT7P8v+D6Zu5HVJ/8vBaQ6QWup2aBLIqLklfQSHMIL/Q4s6g9+HfyNEtgFIIyhFUgN4rqoCEIMJwVyTwcZ2xV4cr4jkKLnlfpywCcf4s/JESabfWUoK5l7jIDjU0oOExwFThPSPdI1oc78plZ3NuD1OB66LDUC0wq06xgU9Bq8Zz2FHiJ3aMFCH9Nk35hCFy707XPgkxInCa2tEc+XVAmBamIrFLIaNVX7lSPB+MlujfwUGMd0Oi1gucs4Ekyaa1Tt+bMqnyzj1A1OLvzXpwX7VgvxdvgdtxiCFRDc/iOCy+K77iTVY5Rsp4A8QIKC9egfY+YAdHrGCeEuB8=}
